version: '3.8'

services:
  app:
    image: ${IMAGE:-rpa-api}:${VERSION:-latest}
    container_name: rpa-api
    ports:
      - "${APP_PORT:-5000}:5000"
    environment:
      - MYSQL_USER=${MYSQL_USER:-rpauser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-rpapassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-rpadb}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
    volumes:
      - ./logs:/app/logs
    networks:
      - rpa-network

networks:
  rpa-network:
    driver: bridge 